INSERT INTO CP_TIPO_CONFIGURACAO(ID_TP_CONFIGURACAO, DSC_TP_CONFIGURACAO, ID_SIT_CONFIGURACAO)
VALUES (36, 'Encerrar', 1);

INSERT INTO CP_MARCADOR(ID_MARCADOR,DESCR_MARCADOR,ID_TP_MARCADOR,ORD_MARCADOR) 
VALUES(62, 'Pendente de Finalização', 1, 15);