-------------------------------------------
--	SCRIPT:CFG SELF SVC
-------------------------------------------

Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,DT_INI_VIG_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,ID_TP_LOTACAO) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL,sysdate,202,10,1);
