--DOCUMENTO DO TIPO PORTARIA NÃO PODE TER SEU NÚMERO SEQUENCIAL REINICIADO.

INSERT INTO CORPORATIVO.CP_CONFIGURACAO(ID_CONFIGURACAO, HIS_DT_INI, ID_SIT_CONFIGURACAO, ID_TP_CONFIGURACAO)
VALUES(CP_CONFIGURACAO_SEQ.nextval, SYSDATE , 2, 34);

INSERT INTO SIGA.EX_CONFIGURACAO(ID_CONFIGURACAO_EX, ID_FORMA_DOC)
VALUES(CORPORATIVO.CP_CONFIGURACAO_SEQ.currval, 6);
